name: currency_exchange
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  copy_with_extension: ^5.0.3
  dartz: ^0.10.1
  bloc_concurrency: ^0.2.4
  get_it: ^7.6.0
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  dio: ^5.4.1
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_screenutil: ^5.9.0
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  copy_with_extension_gen: ^5.0.3
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true